url: https://eyzhao.github.io/
baseurl:

# Site settings
title: Eric Zhao
email: eric@zhao.science
description: "Professional site for Eric Y. Zhao, MD, PhD, radiation oncologist, cancer researcher, data scientist."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/zhaoez
  - title: google scholar
    url: https://scholar.google.com/citations?user=lUGg5RMAAAAJ&hl=en
  - title: github
    url: https://github.com/eyzhao

# Build settings
markdown: kramdown
permalink: pretty
